pipeline {
    agent any

    environment {     
        DOCKERHUB_CREDENTIALS= credentials('dh')     
    }


    stages {          
        stage('Build') {
            steps {
                script {
                    sh "docker build -f app/Dockerfile -t lceballosa1/cicd_challenge:$BUILD_NUMBER ."
                }
                echo 'Build done!'
            }
        }
        stage('Test') {
            steps {
                script {
                    sh ""
                }
                echo 'Test passed!'
            }
        }
        stage('Release') {
            steps {
                script {
                    sh ""
                }
                echo 'Release mounted!'
            }
        }
    }
}