pipeline {
    agent any

    environment {     
        DOCKERHUB_CREDENTIALS= credentials('dh')  
    }


    stages {          
        stage('Build and Test') {
            steps {
                script {
                    sh "docker build -f app/Dockerfile -t $DOCKERHUB_CREDENTIALS_USR/cicd_challenge:1.0.0-$BUILD_NUMBER ./app/"
                    if (env.BRANCH_NAME.startsWith("feature/")) {
                        echo "Build in ${env.BRANCH_NAME}"
                    } else if (env.BRANCH_NAME.startsWith("main")) {
                        echo "Build in ${env.BRANCH_NAME}"
                    }
                }
            }
        }
        stage('Release') {
            steps {
                script {
                    sh "docker login -u $DOCKERHUB_CREDENTIALS_USR -p $DOCKERHUB_CREDENTIALS_PSW"
                    sh "docker push $DOCKERHUB_CREDENTIALS_USR/cicd_challenge:1.0.0-$BUILD_NUMBER"
                    if (env.BRANCH_NAME.startsWith("feature/")) { 
                        echo "Realsed in ${env.BRANCH_NAME}"
                    }  else if (env.BRANCH_NAME.startsWith("main")) {
                        echo "Build in ${env.BRANCH_NAME}"
                    }                  
                }
                
            }
        }
        stage('Deploy') {
            input "Do u want to deploy?"
            milestone()
            agent { 
                label 'slave1'
            }
            steps {
                script {
                    sh "docker login -u $DOCKERHUB_CREDENTIALS_USR -p $DOCKERHUB_CREDENTIALS_PSW"
                    sh "docker run -p 3000:3000 $DOCKERHUB_CREDENTIALS_USR/cicd_challenge:1.0.0-$BUILD_NUMBER"
                    echo 'Release mounted! siu'
                    if (env.BRANCH_NAME.startsWith("feature/")) {
                        echo "Deploy in ${env.BRANCH_NAME}"
                    } else if (env.BRANCH_NAME.startsWith("main")) {
                        echo "Deploy in ${env.BRANCH_NAME}"
                    }
                    
                }
                
            }
        }
    }
}
